/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package burp.ui;

import java.awt.Color;
import java.util.EventListener;

import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author kali
 */
public class ClosableTabComponent extends javax.swing.JPanel {
    private final CloseListener closeListener;

    public void setText(String text) {
        nameLabel.setText(text);
    }

    /**
     * Creates new form ClosableTabComponent
     */
    public ClosableTabComponent(String title, CloseListener onClose) {
        this.closeListener = onClose;
        
        initComponents();
        nameLabel.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        nameLabel.setText("TEMP");
        add(nameLabel, new java.awt.GridBagConstraints());

        closeBtn.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        closeBtn.setText("X");
        closeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeBtn.setContentAreaFilled(false);
        closeBtn.setMargin(new java.awt.Insets(0, 5, 0, 5));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(closeBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        if (closeListener != null) {
            closeListener.close();
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        closeBtn.setBorder(new LineBorder(Color.black, 1));
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBorder(new EmptyBorder(1, 1, 1, 1));
    }//GEN-LAST:event_closeBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    public interface CloseListener extends EventListener {
		void close();
	}
}
