/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package burp.ui;

import java.awt.Color;
import java.awt.Component;
import java.util.EventListener;

import javax.swing.JTabbedPane;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author kali
 */
public class CloseableTabComponent extends javax.swing.JPanel {
    private final CloseListener closeListener;
    private final JTabbedPane parent;

    private boolean isActive = true;
    public void setActive(boolean isActive) {
        this.isActive = isActive;
        closeBtn.setEnabled(isActive);
    }

    public void setText(String text) {
        nameTextField.setText(text);
    }

    public void commitRename() {
        String renamed = nameTextField.getText().strip();
        if (renamed.equals("") || renamed.isEmpty()) {
            renamed = " ";
        }

        setText(renamed);
        nameTextField.setEditable(false);
        nameTextField.setFocusable(false);
    }

    /**
     * Creates new form ClosableTabComponent
     */
    public CloseableTabComponent(String title, JTabbedPane parent, CloseListener onClose) {
        this.closeListener = onClose;
        this.parent = parent;

        parent.addChangeListener(e -> {
            Component selected = parent.getTabComponentAt(parent.getSelectedIndex());
            if (selected == this) {
                setActive(true);
            } else {
                setActive(false);
            }
        });
        
        initComponents();

        setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        closeBtn = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        closeBtn.setFont(new java.awt.Font("Cantarell", 0, 10)); // NOI18N
        closeBtn.setText("X");
        closeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        closeBtn.setContentAreaFilled(false);
        closeBtn.setMargin(new java.awt.Insets(0, 5, 0, 5));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(closeBtn, gridBagConstraints);

        nameTextField.setEditable(false);
        nameTextField.setText("TEMP");
        nameTextField.setAutoscrolls(false);
        nameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        nameTextField.setOpaque(true);
        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(nameTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        if (closeListener != null) {
            closeListener.close();
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        if (isActive) {
            closeBtn.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBorder(new EmptyBorder(1, 1, 1, 1));
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        if (!isActive) {
            parent.setSelectedIndex(parent.indexOfTabComponent(this));
        }
    }//GEN-LAST:event_closeBtnMouseClicked

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost
        commitRename();
    }//GEN-LAST:event_nameTextFieldFocusLost

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        commitRename();
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        revalidate();
    }//GEN-LAST:event_nameTextFieldKeyTyped

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        if (!isActive) {
            parent.setSelectedIndex(parent.indexOfTabComponent(this));
            return;
        }

        if (evt.getClickCount() >= 2) {
            nameTextField.setEditable(true);
            nameTextField.setFocusable(true);
            nameTextField.grabFocus();
            nameTextField.selectAll();
        }
    }//GEN-LAST:event_nameTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables

    public interface CloseListener extends EventListener {
		void close();
	}
}
